#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "Usage: $0 <status|start|stop|restart|create-client|delete-client|disable-client|enable-client|get-config|session-stats> <wireguard|openvpn> [name]"
  exit 1
}

if [[ $# -lt 2 ]]; then
  usage
fi

cmd="$1"
backend="$2"
arg3="${3:-}"

case "${backend}" in
  wireguard)
    service="wg-quick@wg0"
    ;;
  openvpn)
    service="openvpn-server@server"
    ;;
  *)
    echo "invalid backend"
    exit 2
    ;;
esac

detect_endpoint_host() {
  local host=""

  # Optional explicit override.
  if [[ -n "${VPNWEB_ENDPOINT_HOST:-}" ]]; then
    host="${VPNWEB_ENDPOINT_HOST}"
  fi

  # Try to detect from network summary generated by installer.
  if [[ -z "${host}" && -f /etc/vpnweb-network-summary ]]; then
    local wan
    wan="$(awk -F'=' '$1=="wan_interface"{print $2; exit}' /etc/vpnweb-network-summary)"
    if [[ -n "${wan}" ]]; then
      host="$(ip -o -4 addr show dev "${wan}" scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -n1)"
    fi
  fi

  # Fallback: default route device global IPv4.
  if [[ -z "${host}" ]]; then
    local wan2
    wan2="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev") {print $(i+1); exit}}')"
    if [[ -n "${wan2}" ]]; then
      host="$(ip -o -4 addr show dev "${wan2}" scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -n1)"
    fi
  fi

  if [[ -z "${host}" ]]; then
    host="REPLACE_WITH_SERVER_IP"
  fi

  echo "${host}"
}

wg_server_pubkey() {
  local pub
  pub="$(wg show wg0 public-key 2>/dev/null || true)"
  if [[ -n "${pub}" ]]; then
    printf '%s' "${pub}"
    return
  fi

  local priv
  priv="$(awk -F' = ' '/^PrivateKey = /{print $2; exit}' /etc/wireguard/wg0.conf)"
  printf '%s' "${priv}" | wg pubkey
}

wg_next_ip() {
  local used
  used="$(grep -RhoE '^Address = 10\.66\.66\.[0-9]+/32$' /etc/wireguard/clients 2>/dev/null | sed -E 's/^Address = 10\.66\.66\.([0-9]+)\/32$/\1/' || true)"
  for i in $(seq 2 254); do
    if ! grep -qx "${i}" <<<"${used}"; then
      echo "10.66.66.${i}/32"
      return
    fi
  done
  echo "no free ip" >&2
  exit 3
}

wg_ipv6_enabled() {
  if [[ -f /etc/vpnweb-network-summary ]]; then
    [[ "$(awk -F'=' '$1=="ipv6_global_on_wan"{print $2; exit}' /etc/vpnweb-network-summary || true)" == "1" ]]
    return
  fi
  return 1
}

wg_ipv6_for_v4() {
  local addr4="$1"
  local host
  host="${addr4#10.66.66.}"
  host="${host%/32}"
  if [[ ! "${host}" =~ ^[0-9]+$ ]]; then
    return 1
  fi
  echo "fd42:42:42::${host}/128"
}

wg_sanitize_name() {
  local name="$1"
  [[ "${name}" =~ ^[a-zA-Z0-9_-]{3,32}$ ]]
}

wg_create_client() {
  local name="$1"
  wg_sanitize_name "${name}" || { echo "bad name" >&2; exit 4; }

  mkdir -p /etc/wireguard/clients
  local client_conf="/etc/wireguard/clients/${name}.conf"
  if [[ -f "${client_conf}" ]]; then
    echo "exists" >&2
    exit 5
  fi

  local c_priv c_pub psk addr addr6 server_pub endpoint_host peer_allowed iface_addr
  c_priv="$(wg genkey)"
  c_pub="$(printf '%s' "${c_priv}" | wg pubkey)"
  psk="$(wg genpsk)"
  addr="$(wg_next_ip)"
  addr6=""
  if wg_ipv6_enabled; then
    addr6="$(wg_ipv6_for_v4 "${addr}" || true)"
  fi
  server_pub="$(wg_server_pubkey)"
  endpoint_host="$(detect_endpoint_host)"
  iface_addr="${addr}"
  peer_allowed="${addr}"
  if [[ -n "${addr6}" ]]; then
    iface_addr="${addr},${addr6}"
    peer_allowed="${addr},${addr6}"
  fi

  cat > "${client_conf}" <<CFG
# TunnelName: ${name}
[Interface]
PrivateKey = ${c_priv}
Address = ${iface_addr}
DNS = 1.1.1.1

[Peer]
PublicKey = ${server_pub}
PresharedKey = ${psk}
Endpoint = ${endpoint_host}:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
CFG
  chmod 600 "${client_conf}"

  cat >> /etc/wireguard/wg0.conf <<PEER

# vpnweb:${name}
[Peer]
PublicKey = ${c_pub}
PresharedKey = ${psk}
AllowedIPs = ${peer_allowed}
PEER

  wg syncconf wg0 <(wg-quick strip wg0)

  printf 'OK|%s|%s\n' "${name}" "${iface_addr}"
}

wg_delete_client() {
  local name="$1"
  wg_sanitize_name "${name}" || { echo "bad name" >&2; exit 4; }
  local client_conf="/etc/wireguard/clients/${name}.conf"

  if [[ ! -f "${client_conf}" ]]; then
    echo "missing" >&2
    exit 6
  fi

  awk -v marker="# vpnweb:${name}" '
    $0 == marker {skip=1; saw_peer=0; next}
    skip && /^\[Peer\]$/ {saw_peer=1; next}
    skip && saw_peer && NF==0 {skip=0; saw_peer=0; next}
    skip {next}
    {print}
  ' /etc/wireguard/wg0.conf > /etc/wireguard/wg0.conf.tmp
  mv /etc/wireguard/wg0.conf.tmp /etc/wireguard/wg0.conf

  wg syncconf wg0 <(wg-quick strip wg0)
  rm -f "${client_conf}"
  echo "OK"
}

wg_get_config() {
  local name="$1"
  wg_sanitize_name "${name}" || { echo "bad name" >&2; exit 4; }
  local path="/etc/wireguard/clients/${name}.conf"
  [[ -f "${path}" ]] || exit 6
  cat "${path}"
}

ovpn_paths() {
  EASYRSA_DIR="/etc/openvpn/easy-rsa"
  CLIENTS_DIR="/etc/openvpn/clients"
  SERVER_DIR="/etc/openvpn/server"
  EASYRSA_BIN="${EASYRSA_DIR}/easyrsa"
}

ovpn_sanitize_name() {
  local name="$1"
  [[ "${name}" =~ ^[a-zA-Z0-9_-]{3,32}$ ]]
}

ovpn_extract_cert() {
  awk '/-----BEGIN CERTIFICATE-----/{p=1} p; /-----END CERTIFICATE-----/{p=0}' "$1"
}

ovpn_create_client() {
  local name="$1"
  ovpn_paths
  local endpoint_host
  endpoint_host="$(detect_endpoint_host)"

  if ! ovpn_sanitize_name "${name}"; then
    echo "bad name" >&2
    exit 4
  fi

  mkdir -p "${CLIENTS_DIR}"
  local ovpn_path="${CLIENTS_DIR}/${name}.ovpn"

  if [[ -f "${EASYRSA_DIR}/pki/issued/${name}.crt" ]]; then
    echo "exists" >&2
    exit 5
  fi

  cd "${EASYRSA_DIR}"
  "${EASYRSA_BIN}" --batch build-client-full "${name}" nopass >/dev/null

  {
    cat <<CFG
client
dev tun
tun-ipv6
proto udp
remote ${endpoint_host} 1194
resolv-retry infinite
nobind
persist-key
persist-tun
redirect-gateway def1
dhcp-option DNS 1.1.1.1
dhcp-option DNS 8.8.8.8
explicit-exit-notify 2
remote-cert-tls server
cipher AES-256-GCM
auth SHA256
tls-version-min 1.2
verb 3
key-direction 1

<ca>
CFG
    cat "${EASYRSA_DIR}/pki/ca.crt"
    cat <<CFG
</ca>
<cert>
CFG
    ovpn_extract_cert "${EASYRSA_DIR}/pki/issued/${name}.crt"
    cat <<CFG
</cert>
<key>
CFG
    cat "${EASYRSA_DIR}/pki/private/${name}.key"
    cat <<CFG
</key>
<tls-crypt>
CFG
    cat "${SERVER_DIR}/ta.key"
    cat <<CFG
</tls-crypt>
CFG
  } > "${ovpn_path}"

  chmod 600 "${ovpn_path}"
  printf 'OK|%s\n' "${name}"
}

ovpn_delete_client() {
  local name="$1"
  ovpn_paths

  if ! ovpn_sanitize_name "${name}"; then
    echo "bad name" >&2
    exit 4
  fi

  if [[ ! -f "${EASYRSA_DIR}/pki/issued/${name}.crt" ]]; then
    echo "missing" >&2
    exit 6
  fi

  cd "${EASYRSA_DIR}"
  "${EASYRSA_BIN}" --batch revoke "${name}" >/dev/null
  "${EASYRSA_BIN}" gen-crl >/dev/null
  install -m 644 "${EASYRSA_DIR}/pki/crl.pem" "${SERVER_DIR}/crl.pem"
  systemctl restart openvpn-server@server || true

  rm -f "${CLIENTS_DIR}/${name}.ovpn"
  echo "OK"
}

ovpn_get_config() {
  local name="$1"
  ovpn_paths

  local path="${CLIENTS_DIR}/${name}.ovpn"
  [[ -f "${path}" ]] || exit 6
  cat "${path}"
}

wg_disable_client() {
  local name="$1"
  wg_sanitize_name "${name}" || { echo "bad name" >&2; exit 4; }
  local conf="/etc/wireguard/clients/${name}.conf"
  [[ -f "${conf}" ]] || exit 6

  awk -v marker="# vpnweb:${name}" '
    $0 == marker {skip=1; saw_peer=0; next}
    skip && /^\[Peer\]$/ {saw_peer=1; next}
    skip && saw_peer && NF==0 {skip=0; saw_peer=0; next}
    skip {next}
    {print}
  ' /etc/wireguard/wg0.conf > /etc/wireguard/wg0.conf.tmp
  mv /etc/wireguard/wg0.conf.tmp /etc/wireguard/wg0.conf
  wg syncconf wg0 <(wg-quick strip wg0)
  echo "OK"
}

wg_enable_client() {
  local name="$1"
  wg_sanitize_name "${name}" || { echo "bad name" >&2; exit 4; }
  local conf="/etc/wireguard/clients/${name}.conf"
  [[ -f "${conf}" ]] || exit 6

  if grep -q "^# vpnweb:${name}$" /etc/wireguard/wg0.conf; then
    echo "OK"
    return
  fi

  local c_priv c_pub psk addr allowed
  c_priv="$(awk -F' = ' '/^PrivateKey = /{print $2; exit}' "${conf}")"
  psk="$(awk -F' = ' '/^PresharedKey = /{print $2; exit}' "${conf}")"
  addr="$(awk -F' = ' '/^Address = /{print $2; exit}' "${conf}")"
  allowed="${addr}"
  c_pub="$(printf '%s' "${c_priv}" | wg pubkey)"

  cat >> /etc/wireguard/wg0.conf <<PEER

# vpnweb:${name}
[Peer]
PublicKey = ${c_pub}
PresharedKey = ${psk}
AllowedIPs = ${allowed}
PEER
  wg syncconf wg0 <(wg-quick strip wg0)
  echo "OK"
}

wg_session_stats() {
  mkdir -p /etc/wireguard/clients
  local now
  now="$(date +%s)"
  local dump
  dump="$(wg show wg0 dump 2>/dev/null || true)"

  shopt -s nullglob
  local conf
  for conf in /etc/wireguard/clients/*.conf; do
    local name c_priv c_pub line endpoint hs rx tx age state last_seen
    name="$(basename "${conf}" .conf)"
    c_priv="$(awk -F' = ' '/^PrivateKey = /{print $2; exit}' "${conf}")"
    [[ -n "${c_priv}" ]] || continue
    c_pub="$(printf '%s' "${c_priv}" | wg pubkey)"
    line="$(printf '%s\n' "${dump}" | awk -F'\t' -v pub="${c_pub}" '$1==pub {print; exit}')"

    if [[ -z "${line}" ]]; then
      printf '%s|offline|0|0||\n' "${name}"
      continue
    fi

    endpoint="$(printf '%s' "${line}" | awk -F'\t' '{print $3}')"
    hs="$(printf '%s' "${line}" | awk -F'\t' '{print $5}')"
    rx="$(printf '%s' "${line}" | awk -F'\t' '{print $6}')"
    tx="$(printf '%s' "${line}" | awk -F'\t' '{print $7}')"
    last_seen=""
    state="idle"

    if [[ "${hs}" =~ ^[0-9]+$ ]] && [[ "${hs}" -gt 0 ]]; then
      age=$(( now - hs ))
      if [[ "${age}" -le 180 ]]; then
        state="online"
      else
        state="seen"
      fi
      last_seen="$(date -d "@${hs}" '+%Y-%m-%d %H:%M:%S' 2>/dev/null || true)"
    fi

    if [[ "${endpoint}" == "(none)" ]]; then
      endpoint=""
    fi

    printf '%s|%s|%s|%s|%s|%s\n' "${name}" "${state}" "${rx:-0}" "${tx:-0}" "${last_seen}" "${endpoint}"
  done
  shopt -u nullglob
}

ovpn_disable_client() {
  local name="$1"
  ovpn_paths
  if ! ovpn_sanitize_name "${name}"; then
    echo "bad name" >&2
    exit 4
  fi
  touch "${SERVER_DIR}/disabled-clients.txt"
  if ! grep -Fxq "${name}" "${SERVER_DIR}/disabled-clients.txt"; then
    echo "${name}" >> "${SERVER_DIR}/disabled-clients.txt"
  fi
  echo "OK"
}

ovpn_enable_client() {
  local name="$1"
  ovpn_paths
  if ! ovpn_sanitize_name "${name}"; then
    echo "bad name" >&2
    exit 4
  fi
  touch "${SERVER_DIR}/disabled-clients.txt"
  grep -Fxv "${name}" "${SERVER_DIR}/disabled-clients.txt" > "${SERVER_DIR}/disabled-clients.txt.tmp" || true
  mv "${SERVER_DIR}/disabled-clients.txt.tmp" "${SERVER_DIR}/disabled-clients.txt"
  echo "OK"
}

ovpn_session_stats() {
  ovpn_paths
  local status_file="/var/log/openvpn/openvpn-status.log"
  [[ -f "${status_file}" ]] || return 0

  awk -F',' '
    BEGIN {
      in_clients = 0
      csv = 0
    }
    /^CLIENT_LIST,/ {
      csv = 1
      name = $2
      endpoint = $3
      rx = $4
      tx = $5
      last_seen = $6
      print name "|online|" rx "|" tx "|" last_seen "|" endpoint
      next
    }
    /^Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since$/ {
      in_clients = 1
      next
    }
    /^ROUTING TABLE$/ || /^GLOBAL STATS$/ || /^END$/ {
      in_clients = 0
      next
    }
    csv == 0 && in_clients == 1 && NF >= 5 {
      name = $1
      endpoint = $2
      rx = $3
      tx = $4
      last_seen = $5
      for (i = 6; i <= NF; i++) {
        last_seen = last_seen "," $i
      }
      print name "|online|" rx "|" tx "|" last_seen "|" endpoint
    }
  ' "${status_file}"
}

case "${cmd}" in
  status)
    systemctl is-active "${service}" || true
    ;;
  start)
    systemctl start "${service}"
    ;;
  stop)
    systemctl stop "${service}"
    ;;
  restart)
    systemctl restart "${service}"
    ;;
  create-client)
    [[ -n "${arg3}" ]] || usage
    if [[ "${backend}" == "wireguard" ]]; then
      wg_create_client "${arg3}"
    else
      ovpn_create_client "${arg3}"
    fi
    ;;
  delete-client)
    [[ -n "${arg3}" ]] || usage
    if [[ "${backend}" == "wireguard" ]]; then
      wg_delete_client "${arg3}"
    else
      ovpn_delete_client "${arg3}"
    fi
    ;;
  disable-client)
    [[ -n "${arg3}" ]] || usage
    if [[ "${backend}" == "wireguard" ]]; then
      wg_disable_client "${arg3}"
    else
      ovpn_disable_client "${arg3}"
    fi
    ;;
  enable-client)
    [[ -n "${arg3}" ]] || usage
    if [[ "${backend}" == "wireguard" ]]; then
      wg_enable_client "${arg3}"
    else
      ovpn_enable_client "${arg3}"
    fi
    ;;
  get-config)
    [[ -n "${arg3}" ]] || usage
    if [[ "${backend}" == "wireguard" ]]; then
      wg_get_config "${arg3}"
    else
      ovpn_get_config "${arg3}"
    fi
    ;;
  session-stats)
    if [[ "${backend}" == "wireguard" ]]; then
      wg_session_stats
    else
      ovpn_session_stats
    fi
    ;;
  *)
    usage
    ;;
esac
